delete from country where code > 0;
/*-------------------------------------------------------------------*/
insert into country (code, name) values (1473, 'Grenada');
insert into country (code, name) values (1868, 'Trinidad and Tobago');
insert into country (code, name) values (1869, 'Saint Kitts and Nevis');
insert into country (code, name) values (594, 'French Guiana');
insert into country (code, name) values (297, 'Aruba');
insert into country (code, name) values (1784, 'Saint Vincent and the Granadines');
insert into country (code, name) values (599, 'Netherlands Antilles');
insert into country (code, name) values (596, 'Martinique');
insert into country (code, name) values (1284, 'British Virgin Islands');
insert into country (code, name) values (1721, 'Sint Maarten');
insert into country (code, name) values (590, 'Guadeloupe');
insert into country (code, name) values (1268, 'Antigua and Barbuda');
insert into country (code, name) values (1758, 'Saint Lucia');
insert into country (code, name) values (1876, 'Jamaica');
insert into country (code, name) values (1767, 'Dominica');
insert into country (code, name) values (1246, 'Barbados');
insert into country (code, name) values (597, 'Suriname');
insert into country (code, name) values (592, 'Guyana');
insert into country (code, name) values (1441, 'Bermuda');
insert into country (code, name) values (590590, 'Saint Martin');
insert into country (code, name) values (1345, 'Cayman Islands');
insert into country (code, name) values (1787, 'Puerto Rico');
insert into country (code, name) values (509, 'Haiti');
insert into country (code, name) values (1809, 'Dominican Republic');
insert into country (code, name) values (503, 'Cuba');
insert into country (code, name) values (1664, 'Monserrat');
insert into country (code, name) values (1264, 'Anguila');
/*-------------------------------------------------------------------*/
insert into country (code, name) values (966, 'Saudi Arabia');
insert into country (code, name) values (1, 'United States');
insert into country (code, name) values (54, 'Argentina');
insert into country (code, name) values (225, 'Ivory Coast');
insert into country (code, name) values (45, 'Denmark');
insert into country (code, name) values (52, 'Mexico');
insert into country (code, name) values (234, 'Nigeria');
insert into country (code, name) values (81, 'Japan');
insert into country (code, name) values (55, 'Brazil');
insert into country (code, name) values (61, 'Australia');
insert into country (code, name) values (598, 'Uruguay');
insert into country (code, name) values (420, 'Czech Republic');
insert into country (code, name) values (27, 'South Africa');
insert into country (code, name) values (971, 'United Arab Emirates');
insert into country (code, name) values (591, 'Bolivia');
insert into country (code, name) values (20, 'Egypt');
insert into country (code, name) values (49, 'Germany');
insert into country (code, name) values (64, 'New Zealand');
insert into country (code, name) values (33, 'France');
insert into country (code, name) values (82, 'South Korea');
insert into country (code, name) values (1613, 'Canada');
insert into country (code, name) values (237, 'Cameroon');
insert into country (code, name) values (57, 'Colombia');
insert into country (code, name) values (90, 'Turkey');
insert into country (code, name) values (30, 'Greece');
insert into country (code, name) values (216, 'Tunisia');
insert into country (code, name) values (34, 'Spain');
insert into country (code, name) values (964, 'Iraq');
insert into country (code, name) values (39, 'Italy');
insert into country (code, name) values (689, 'Tahiti');
insert into country (code, name) values (7, 'Russia');
insert into country (code, name) values (56, 'Chile');
insert into country (code, name) values (351, 'Portugal');
/*-------------------------------------------------------------------*/
insert into country (code, name) values (216, 'Tunisia');
insert into country (code, name) values (504, 'Honduras');
insert into country (code, name) values (36, 'Hungary');
insert into country (code, name) values (212, 'Morocco');
insert into country (code, name) values (98, 'Iran');
insert into country (code, name) values (7097, 'Soviet Union');
insert into country (code, name) values (595, 'Paraguay');
insert into country (code, name) values (43, 'Austria');
insert into country (code, name) values (213, 'Algeria');
insert into country (code, name) values (48, 'Poland');
insert into country (code, name) values (38, 'Yugoslavia');
insert into country (code, name) values (62, 'Indonesia');
insert into country (code, name) values (224, 'Guinea');
insert into country (code, name) values (974, 'Qatar');
insert into country (code, name) values (40, 'Romania');
insert into country (code, name) values (49228, 'West Germany');
insert into country (code, name) values (4420, 'England');
insert into country (code, name) values (44141, 'Scotland');
insert into country (code, name) values (42, 'Czechoslovakia');
insert into country (code, name) values (86, 'China');
insert into country (code, name) values (31, 'Netherlands');
insert into country (code, name) values (359, 'Bulgaria');
insert into country (code, name) values (353, 'Republic of Ireland');
insert into country (code, name) values (228, 'Togo');
insert into country (code, name) values (4930, 'East Germany');
insert into country (code, name) values (973, 'Bahrain');
insert into country (code, name) values (963, 'Syria');
insert into country (code, name) values (506, 'Costa Rica');
insert into country (code, name) values (223, 'Mali');
insert into country (code, name) values (47, 'Norway');
insert into country (code, name) values (46, 'Sweden');
insert into country (code, name) values (233, 'Ghana');
insert into country (code, name) values (257, 'Burundi');
insert into country (code, name) values (60, 'Malaysia');
insert into country (code, name) values (32, 'Belgium');
insert into country (code, name) values (385, 'Croatia');
insert into country (code, name) values (73, 'Kazakhstan');
insert into country (code, name) values (260, 'Zambia');
insert into country (code, name) values (358, 'Finland');
insert into country (code, name) values (380, 'Ukraine');
insert into country (code, name) values (244, 'Angola');
insert into country (code, name) values (593, 'Ecuador');
insert into country (code, name) values (251, 'Ethiopia');	
insert into country (code, name) values (421, 'Slovakia');
insert into country (code, name) values (507, 'Panama');
insert into country (code, name) values (226, 'Burkina Faso');
insert into country (code, name) values (998, 'Uzbekistan');
insert into country (code, name) values (229, 'Benin');
insert into country (code, name) values (41, 'Switzerland');
insert into country (code, name) values (242, 'Republic of the Congo');
insert into country (code, name) values (962, 'Jordan');
insert into country (code, name) values (220, 'Gambia');
insert into country (code, name) values (850, 'North Korea');
insert into country (code, name) values (58, 'Venezuela');
insert into country (code, name) values (502, 'Guatemala');
insert into country (code, name) values (53, 'Cuba');
insert into country (code, name) values (503, 'El Salvador');
insert into country (code, name) values (95, 'Myanmar');
insert into country (code, name) values (221, 'Senegal');
insert into country (code, name) values (381, 'Serbia');
insert into country (code, name) values (679, 'Fiji');
insert into country (code, name) values (678, 'Vanuatu');
insert into country (code, name) values (84, 'Vietnam');
/*-------------------------------------------------------------------*/
insert into country (code, name) values (4420, 'Upton Park F.C.');
insert into country (code, name) values (331, 'USFSA XI');
insert into country (code, name) values (322, 'Université de Bruxelles');
insert into country (code, name) values (1519, 'Galt Football Club');
insert into country (code, name) values (13141850, 'Christian Brothers College');
insert into country (code, name) values (13141015, 'St. Rose Parish');
insert into country (code, name) values (90232, 'Smyrna ');
insert into country (code, name) values (30231, 'Thessaloniki');
insert into country (code, name) values (3021, 'Athens');
insert into country (code, name) values (44, 'United Kingdom');
insert into country (code, name) values (3399, 'France B');
insert into country (code, name) values (3398, 'France A');
insert into country (code, name) values (4203, 'Bohemia');
insert into country (code, name) values (7812, 'Russian Empire');
insert into country (code, name) values (352, 'Luxembourg');
insert into country (code, name) values (370, 'Lithuania');
insert into country (code, name) values (372, 'Estonia');
insert into country (code, name) values (371, 'Latvia');
insert into country (code, name) values (3531, 'Irish Free State');
insert into country (code, name) values (51, 'Peru');
insert into country (code, name) values (93, 'Afghanistan');
insert into country (code, name) values (91, 'India');
insert into country (code, name) values (599, 'Netherlands Antilles');
insert into country (code, name) values (66, 'Thailand');
insert into country (code, name) values (886, 'China Taipei');
insert into country (code, name) values (972, 'Israel');
insert into country (code, name) values (951, 'Burma');
insert into country (code, name) values (249, 'Sudan');
insert into country (code, name) values (965, 'Kuwait');
insert into country (code, name) values (38111, 'Serbia and Montenegro');
insert into country (code, name) values (38220, 'FR Yugoslavia');
insert into country (code, name) values (382, 'Montenegro');
insert into country (code, name) values (241, 'Gabon');
insert into country (code, name) values (375, 'Belarus');
insert into country (code, name) values (37517, 'Commonwealth of Independent States');
-------------------------------------------------------------------*/
insert into country (code, name) values (386, 'Slovenia');
insert into country (code, name) values (355, 'Albania');
insert into country (code, name) values (4429, 'Wales');
insert into country (code, name) values (4428, 'Northern Ireland');
insert into country (code, name) values (354, 'Iceland');
/*-------------------------------------------------------------------*/