delete from country where code > 0;
/*-------------------------------------------------------------------*/
insert into country (code, name) values (4420, 'Upton Park F.C.');
insert into country (code, name) values (331, 'USFSA XI');
insert into country (code, name) values (322, 'Université de Bruxelles');
insert into country (code, name) values (1519, 'Galt Football Club');
insert into country (code, name) values (13141850, 'Christian Brothers College');
insert into country (code, name) values (13141015, 'St. Rose Parish');
insert into country (code, name) values (45, 'Denmark');
insert into country (code, name) values (90232, 'Smyrna ');
insert into country (code, name) values (30231, 'Thessaloniki');
insert into country (code, name) values (3021, 'Athens');
insert into country (code, name) values (31, 'Netherlands');
insert into country (code, name) values (36, 'Hungary');
insert into country (code, name) values (44, 'United Kingdom');
insert into country (code, name) values (46, 'Sweden');
insert into country (code, name) values (3399, 'France B');
insert into country (code, name) values (3398, 'France A');
insert into country (code, name) values (4203, 'Bohemia');
insert into country (code, name) values (39, 'Italy');
insert into country (code, name) values (358, 'Finland');
insert into country (code, name) values (43, 'Austria');
insert into country (code, name) values (49, 'Germany');
insert into country (code, name) values (47, 'Norway');
insert into country (code, name) values (7812, 'Russian Empire');
insert into country (code, name) values (38, 'Yugoslavia');
insert into country (code, name) values (42, 'Czechoslovakia');
insert into country (code, name) values (20, 'Egypt');
insert into country (code, name) values (34, 'Spain');
insert into country (code, name) values (30, 'Greece');
insert into country (code, name) values (352, 'Luxembourg');
insert into country (code, name) values (33, 'France');
insert into country (code, name) values (32, 'Belgium');
insert into country (code, name) values (41, 'Switzerland');
insert into country (code, name) values (370, 'Lithuania');
insert into country (code, name) values (90, 'Turkey');
insert into country (code, name) values (1, 'United States');
insert into country (code, name) values (372, 'Estonia');
insert into country (code, name) values (598, 'Uruguay');
insert into country (code, name) values (48, 'Poland');
insert into country (code, name) values (40, 'Romania');
insert into country (code, name) values (371, 'Latvia');
insert into country (code, name) values (359, 'Bulgaria');
insert into country (code, name) values (3531, 'Irish Free State');
insert into country (code, name) values (351, 'Portugal');
insert into country (code, name) values (56, 'Chile');
insert into country (code, name) values (54, 'Argentina');
insert into country (code, name) values (52, 'Mexico');
insert into country (code, name) values (81, 'Japan');
insert into country (code, name) values (86, 'China');
insert into country (code, name) values (51, 'Peru');
insert into country (code, name) values (353, 'Republic of Ireland');
insert into country (code, name) values (93, 'Afghanistan');
insert into country (code, name) values (91, 'India');
insert into country (code, name) values (82, 'South Korea');
insert into country (code, name) values (7097, 'Soviet Union');
insert into country (code, name) values (55, 'Brazil');
insert into country (code, name) values (49228, 'West Germany');
insert into country (code, name) values (599, 'Netherlands Antilles');
insert into country (code, name) values (66, 'Thailand');
insert into country (code, name) values (61, 'Australia');
insert into country (code, name) values (62, 'Indonesia');
insert into country (code, name) values (886, 'China Taipei');
insert into country (code, name) values (216, 'Tunisia');
-------------------------------------------------------------------*/
insert into country (code, name) values (381, 'Serbia');
insert into country (code, name) values (420, 'Czech Republic');
insert into country (code, name) values (7, 'Russia');
insert into country (code, name) values (4420, 'England');
insert into country (code, name) values (37517, 'Commonwealth of Independent States');
insert into country (code, name) values (44141, 'Scotland');
insert into country (code, name) values (385, 'Croatia');
insert into country (code, name) values (386, 'Slovenia');
insert into country (code, name) values (38111, 'FR Yugoslavia');
insert into country (code, name) values (380, 'Ukraine');
insert into country (code, name) values (355, 'Albania');
insert into country (code, name) values (4429, 'Wales');
insert into country (code, name) values (421, 'Slovakia');
insert into country (code, name) values (4428, 'Northern Ireland');
insert into country (code, name) values (354, 'Iceland');
/*-------------------------------------------------------------------*/
insert into country (code, name) values (1613, 'Canada');