insert into game_type (id, name) values 
(1,  'Qualifier'),
(2,  'Group Stage'),
(3,  'Quarter-Final'),
(4,  'Semi-Final'),
(5,  'Third Place'),
(6,  'Final'),
(7,  'Play-Off'),
(8,  'Final Round'),
(9,  'Round of 16'),
(10, 'Exhibition'),
(11, 'Play-Off Exhibition'),
(12, 'Final Second Place'),
(13, 'Bronze Medal Match'),
(14, 'Gold Medal Match'),
(15, 'First Round');