delete from tournament where code > 0;
insert into tournament (code, country) values (1900, 33);
insert into tournament (code, country) values (1904, 1);
insert into tournament (code, country) values (1906, 30);
insert into tournament (code, country) values (1908, 44);
insert into tournament (code, country) values (1912, 46);
insert into tournament (code, country) values (1920, 32);
insert into tournament (code, country) values (1924, 33);
insert into tournament (code, country) values (1928, 31);
insert into tournament (code, country) values (1936, 49);
insert into tournament (code, country) values (1948, 44);
insert into tournament (code, country) values (1952, 358);
insert into tournament (code, country) values (1956, 61);
insert into tournament (code, country) values (1960, 39);