delete from country where code > 0;
/*-------------------------------------------------------------------*/
insert into country (code, name) values (31, 'Netherlands');
insert into country (code, name) values (595, 'Paraguay');
insert into country (code, name) values (45, 'Denmark');
insert into country (code, name) values (213, 'Algeria');
insert into country (code, name) values (55, 'Brazil');
insert into country (code, name) values (36, 'Hungary');
insert into country (code, name) values (34, 'Spain');
insert into country (code, name) values (966, 'Saudi Arabia');
insert into country (code, name) values (32, 'Belgium');
insert into country (code, name) values (54, 'Argentina');
insert into country (code, name) values (1613, 'Canada');
insert into country (code, name) values (81, 'Japan');
insert into country (code, name) values (1, 'United States');
insert into country (code, name) values (39, 'Italy');
insert into country (code, name) values (61, 'Australia');
insert into country (code, name) values (263, 'Zimbabwe');
insert into country (code, name) values (852, 'Hong Kong');
insert into country (code, name) values (48, 'Poland');
insert into country (code, name) values (233, 'Nigeria');
insert into country (code, name) values (98, 'Iran');
insert into country (code, name) values (506, 'Costa Rica');
insert into country (code, name) values (7, 'Russia');
insert into country (code, name) values (86, 'China');
insert into country (code, name) values (20, 'Egypt');
insert into country (code, name) values (380, 'Ukraine');
insert into country (code, name) values (598, 'Uruguay');
insert into country (code, name) values (60, 'Malaysia');
insert into country (code, name) values (53, 'Cuba');
insert into country (code, name) values (502, 'Guatemala');
insert into country (code, name) values (351, 'Portugal');
insert into country (code, name) values (76, 'Kazakhstan');
insert into country (code, name) values (66, 'Thailand');
insert into country (code, name) values (385, 'Croatia');
insert into country (code, name) values (886, 'Chinese Taipei');
insert into country (code, name) values (420, 'Czech Republic');
insert into country (code, name) values (677, 'Solomon Islands');
insert into country (code, name) values (218, 'Libya');