delete from country where code > 0;
/*-------------------------------------------------------------------*/
insert into country (code, name) values (249, 'Sudan');
insert into country (code, name) values (20, 'Egypt');
insert into country (code, name) values (251, 'Ethiopia');
insert into country (code, name) values (27, 'South Africa');
insert into country (code, name) values (202, 'United Arab Republic');
insert into country (code, name) values (216, 'Tunisia');
insert into country (code, name) values (256, 'Uganda');
insert into country (code, name) values (233, 'Ghana');
insert into country (code, name) values (234, 'Nigeria');
insert into country (code, name) values (221, 'Senegal');
insert into country (code, name) values (225, 'Ivory Coast');
insert into country (code, name) values (2439, 'Congo-Léopoldville');
insert into country (code, name) values (2431, 'Congo-Kinshasa');
insert into country (code, name) values (2438, 'Zaire');
insert into country (code, name) values (243, 'Democratic Republic of the Congo');
insert into country (code, name) values (213, 'Algeria');
insert into country (code, name) values (2422228, 'Congo-Brazzaville');
insert into country (code, name) values (242, 'Republic of the Congo');
insert into country (code, name) values (237, 'Cameroon');
insert into country (code, name) values (224, 'Guinea');
insert into country (code, name) values (254, 'Kenya');
insert into country (code, name) values (223, 'Mali');
insert into country (code, name) values (228, 'Togo');
insert into country (code, name) values (212, 'Morocco');
insert into country (code, name) values (260, 'Zambia');
insert into country (code, name) values (230, 'Mauritius');