delete from country where code > 0;
insert into country (code, name) values (33, 'France');
insert into country (code, name) values (38, 'Yugoslavia');
insert into country (code, name) values (42, 'Czechoslovakia');
insert into country (code, name) values (7097, 'Soviet Union');
insert into country (code, name) values (381, 'Serbia');
insert into country (code, name) values (420, 'Czech Republic');
insert into country (code, name) values (7, 'Russia');
insert into country (code, name) values (34, 'Spain');
insert into country (code, name) values (36, 'Hungary');
insert into country (code, name) values (45, 'Denmark');
insert into country (code, name) values (39, 'Italy');
insert into country (code, name) values (4420, 'England');
insert into country (code, name) values (32, 'Belgium');
insert into country (code, name) values (49228, 'West Germany');
insert into country (code, name) values (31, 'Netherlands');
/*-------------------------------------------------------------------*/
insert into country (code, name) values (4428, 'Northern Ireland');
insert into country (code, name) values (44141, 'Scotland');
insert into country (code, name) values (4429, 'Wales');
insert into country (code, name) values (1613, 'Canada');